name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/checkout@v4
        with:
          repository: moergo-sc/zmk
          ref: main
          path: src
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v14
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true
      - name: Build Glove80 combined firmware
        run: nix-build config -o combined
      - name: Build Glove80 combined firmare with homerow mods
        run: nix-build config-homerow-mods -o combined-homerow-mods
      - name: Copy result out of nix store
        run: cp combined/glove80.uf2 glove80.uf2
      - name: Copy result out of nix store with homerow mods
        run: cp combined-homerow-mods/glove80.uf2 glove80-homerow-mods.uf2
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ./*.uf2
